import type { Metadata } from "next";
import "./globals.css";
import "react-toastify/ReactToastify.css"
import "react-datepicker/dist/react-datepicker.css"
import {Poppins} from "next/font/google"
 
// const poppins = localFont({
//   src: [{
//     path: "/public/fonts/Poppins-SemiBold.ttf",
//     weight: "700"
//   }
// ],
// variable: "--font-poppins"
// })

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Access By SExpress",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans`}>{children}</body>
    </html>
  );
}
